/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function setInterfaceConfiguration(cryptographicInterface: CryptographicInterface, configuration: InterfaceConfiguration) {
    return invoke()<null>("set_interface_configuration", { cryptographicInterface,configuration })
}

export function getInterfaceConfiguration(cryptographicInterface: CryptographicInterface) {
    return invoke()<InterfaceConfiguration | null>("get_interface_configuration", { cryptographicInterface })
}

export type CryptographicInterface = "Pcsc" | "Cryptoki" | "Webauthn"
export type InterfaceConfiguration = { controller_url: string; group_id: number[] }
